name: Deploy Shiny App

on:
  push:
    branches:
      - master  # Change to 'main' if your default branch is 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.2.1'  # Specify the version of R

    - name: Install required R packages
      run: |
        Rscript -e 'install.packages("rsconnect", repos="https://cloud.r-project.org")'
        Rscript -e 'install.packages("shiny", repos="https://cloud.r-project.org")'
        
    - name: Verify installed packages
      run: |
        Rscript -e 'installed.packages()'  # List installed packages to check if 'rsconnect' is installed

    - name: Deploy to shinyapps.io
      env:
        SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
        SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
      run: |
        Rscript -e 'library(rsconnect)'  # Ensure rsconnect is loaded
        Rscript -e 'rsconnect::setAccountInfo(name="worldhealthorg", token=Sys.getenv("SHINYAPPS_TOKEN"), secret=Sys.getenv("SHINYAPPS_SECRET"))'
        Rscript -e 'rsconnect::deployApp(appFiles=c("app.R"), appName="GSHS", account="worldhealthorg")'
