name: Deploy Shiny App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install R dependencies
      run: |
        Rscript -e 'install.packages(c("shiny", "rsconnect"))'

    - name: Deploy to shinyapps.io
      run: |
        Rscript -e 'rsconnect::setAccountInfo(name="worldhealthorg", token="03F90F4E078FBB4790D4DFF722FC514B", secret="TdfFdKbZBZi0B3bX+kbQQYIh3zrwEe4pC4hbUHg9")'
        Rscript -e 'rsconnect::deployApp(appFiles=c("app.R"), appName="GSHS", account="worldhealthorg")'
