name: Deploy Shiny App

on:
  push:
    branches:
      - master  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.2.1'  # Specify a version of R known to be compatible with rsconnect

    - name: Install rsconnect and other dependencies
      run: |
        Rscript -e 'install.packages(c("shiny", "rsconnect"), repos="https://cloud.r-project.org")'

    - name: Deploy to shinyapps.io
      env:
        SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
        SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
      run: |
        Rscript -e 'rsconnect::setAccountInfo(name="worldhealthorg", token=Sys.getenv("SHINYAPPS_TOKEN"), secret=Sys.getenv("SHINYAPPS_SECRET"))'
        Rscript -e 'rsconnect::deployApp(appFiles=c("app.R"), appName="GSHS", account="worldhealthorg")'

